
version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file setup-es-kibana.yaml --s3-bucket eslex-codepipelinebucket-wtaxzw8yph3w
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - setup-es-kibana.yaml
    - outputSamTemplate.yaml
